# site settings
title: 제주속기사무소
subtitle: 녹취록, 회의록 전문 국가공인 1급 속기사
email: jejuin0915@naver.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/jejusteno" # the subpath of your site, e.g. /blog
url: "https://bare-foot.github.io" # the base hostname & protocol for your site
author: 임승준
street_address: 제주특별자치도 제주시
city: 도로명) 연삼로 401
state: 4층
zip_code: 
country: 지번) 이도2동 1058-22
phone: (064) 702-0915

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
